# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/certificate_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG

# JWT Configuration
jwt.secret=2sN4l7Qv9YxK8mPdR6wZcT5uEiBhGjFn3LpQaXsDvHjK8mPdR6wZcT5uEiBhGjFn
jwt.expiration=86400000